### ISSUE TITLE
karpor helm install not  has ConfigMap 

### ISSUE THREAD

**Issue by Fleezesd** [KusionStack/charts#25]
I use helm with kind to install karpor in the cluster，but this chart I see not has configmap，make server and sync pod pending，please fill it and make a new version

**Comment by elliotxx** [comment]
@Fleezesd Sorry, I just saw this message. Configmap and Secret are generated by Job in Charts. The key code is in this position: https://github.com/KusionStack/charts/blob/71976bfa226961c1fedc45dbd38fc8c493e3d8f2/versions/karpor/0.4.1/templates/job.yml#L17

You can check the status of the Job.

**Comment by Fleezesd** [comment]
ok, thanks for your help
