### ISSUE TITLE
Hardwired namespace

### ISSUE THREAD

**Issue by hayone1** [KusionStack/charts#42]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- Install karpor with helm in another namespace that is not called "karpor"

### 2. What did you expect to see? (Required)
Expected all services to be up.
### 3. What did you see instead (Required)
karpor-syncer tries to contact karpor-server using namespace "karpor" instead of installed namespace.
```
I0725 14:09:53.625871       1 serving.go:342] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
E0725 14:09:53.745719       1 cluster.go:161] "Failed to get API Group-Resources" err="Get \"https://karpor-server.karpor.svc:7443/api?timeout=32s\": dial tcp: lookup karpor-server.karpor.svc on 10.152.183.10:53: no such host"
E0725 14:09:53.745800       1 syncer.go:70] "setup: unable to start manager" err="Get \"https://karpor-server.karpor.svc:7443/api?timeout=32s\": dial tcp: lookup karpor-server.karpor.svc on 10.152.183.10:53: no such host"
E0725 14:09:53.745864       1 run.go:74] "command failed" err="Get \"https://karpor-server.karpor.svc:7443/api?timeout=32s\": dial tcp: lookup karpor-server.karpor.svc on 10.152.183.10:53: no such host"

```
### 4. What is your KusionStack components version? (Required)
- karpor:0.5.3

**Comment by elliotxx** [comment]
@hayone1 Sorry, I just saw this issue. This is a case we overlooked. Let me fully test and fix it.

**Comment by elliotxx** [comment]
@hayone1 We have fixed this issue and can try again.

**Comment by elliotxx** [comment]
@hayone1 Hi, is there any problem now?
